### ISSUE TITLE
Having an issue with Manifest.json

### ISSUE THREAD

**Issue by prkhrv** [kirankumbhar/DjangoPWA#1]
Sir, Please help in editing the manifest.json file

**Comment by hemanth-sp** [comment]
did you got answer ? how to edit

**Comment by prkhrv** [comment]
Nope Brother , I rather Switched to node JS for PWAs

**Comment by hemanth-sp** [comment]
thank you

**Comment by hemanth-sp** [comment]
thank you

**Comment by kirankumbhar** [comment]
Hello @prkhrv Can you elaborate more on what do you mean by the issue with Manifest.json? Sorry for late reply.
